//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProductDetail
    {
        public int ProductId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ProductName { get; set; }
        public string ProductImagePath { get; set; }
    }
}
